---
- hosts: #FillMeUP
  become: false
  vars:
    user_name: #FillMeUP
    pubkey: #FillMeUP
  tasks:
    
    - name: create {{ user_name }} user
      become: true
      user:
        name: "{{ user_name }}"
        comment: "{{ user_name }}"
        home: /home/users/{{ user_name }}
        shell: /bin/bash
      
    - name: create /etc/sudoers.d/{{ user_name }}
      become: true
      file:
        path: /etc/sudoers.d/{{ user_name }}
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: add {{ user_name }} user to /etc/sudoers.d/{{ user_name }}
      become: true
      lineinfile:
        path: /etc/sudoers.d/{{ user_name }}
        line: '{{ user_name }} ALL=NOPASSWD:ALL'
        insertafter: EOF
        state: present

    - name: read key
      # This needs to run on localhost, because that's where
      # the keys are stored.
      delegate_to: localhost
      command: cat {{item}}
      # Register the results of this task in a variable called
      # "keys"
      register: keys
      with_fileglob:
        - "{{ pubkey }}"

    - name: inject authorized key taken from file
      become: true
      authorized_key:
        user: "{{ user_name }}"
        state: present
        manage_dir: yes
        key: "{{item.stdout}}"
      with_items: "{{ keys.results }}"



